[sync]
# Путь к синхронизируемой папке на локальном компьютере
local_folder = /home/evgeniy/test_sync

# Имя папки в облачном хранилище (Яндекс.Диск)
cloud_folder = /PycharmProjects

# Токен доступа к облачному хранилищу (OAuth-токен Яндекс.Диска)
# ВАЖНО: удалите свой токен перед сдачей работы!
token = Token

# Период синхронизации в секундах
sync_period = 60

# Путь к файлу лога
log_file = sync.log
